### ISSUE TITLE
lizard_broken is broken... ?

### ISSUE THREAD

**Issue by robobenklein** [utk-se/CodeAnalytics-analyzer#54]
```
[2020-08-08 08:20:43] [    INFO] [__main__ main] Running analyzer on .
[2020-08-08 08:20:43] [    INFO] [analyzer __init__] ./src/banco/Conta.java
Traceback (most recent call last):
  File "/home/ca-worker/venv/lib/python3.6/site-packages/CAanalyzer-0.0.7-py3.6.egg/caanalyzer/analyzer.py", line 814, in __init__
    match = m.search(lines[i])
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ca-worker/venv/bin/ca-analyzer", line 33, in <module>
    sys.exit(load_entry_point('CAanalyzer==0.0.7', 'console_scripts', 'ca-analyzer')())
  File "/home/ca-worker/venv/lib/python3.6/site-packages/CAanalyzer-0.0.7-py3.6.egg/caanalyzer/__main__.py", line 21, in main
    pp.pprint(analyze(args.repopath))
  File "/home/ca-worker/venv/lib/python3.6/site-packages/CAanalyzer-0.0.7-py3.6.egg/caanalyzer/__main__.py", line 11, in analyze
    repo = analyzer.Repo(path, ignorefile, True)
  File "/home/ca-worker/venv/lib/python3.6/site-packages/CAanalyzer-0.0.7-py3.6.egg/caanalyzer/analyzer.py", line 231, in __init__
    file_obj = File(file_path, file_ext, tabsize)
  File "/home/ca-worker/venv/lib/python3.6/site-packages/CAanalyzer-0.0.7-py3.6.egg/caanalyzer/analyzer.py", line 821, in __init__
    fixed_at_error = self.lizard_broken(lines, file_ext)
TypeError: lizard_broken() missing 1 required positional argument: 'func_list'
```

`/tmp/ca-workdir/ca-worker-coretester1/job-https%3A%2F%2Fgithub.com%2FSousa22ko%2FTestResidenciaNuplam.git` / `ca-analyzer .`

**Comment by jball1997** [comment]
This is strange. Can't replicate on my machine. I fixed the issue with that lizard_broke call but the real issue is that it shouldn't have gotten there in the first place.
